/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_javainterview_core_jni_JavaInterviewJNI */

#ifndef _Included_cn_javainterview_core_jni_JavaInterviewJNI
#define _Included_cn_javainterview_core_jni_JavaInterviewJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_javainterview_core_jni_JavaInterviewJNI
 * Method:    print
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_cn_javainterview_core_jni_JavaInterviewJNI_print
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
